IMAGE title_background "assets/title_background.png" BEST
IMAGE text_credits_default "assets/text_credits_default.png" NONE
IMAGE text_credits_focus "assets/text_credits_focus.png" NONE
IMAGE text_one_player_default "assets/text_one_player_default.png" NONE
IMAGE text_one_player_focus "assets/text_one_player_focus.png" NONE
IMAGE text_options_default "assets/text_options_default.png" NONE
IMAGE text_options_focus "assets/text_options_focus.png" NONE
IMAGE text_two_player_default "assets/text_two_player_default.png" NONE
IMAGE text_two_player_focus "assets/text_two_player_focus.png" NONE
